apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: abac-enroll-restriction-time-bound
  annotations:
    policies.kyverno.io/description: |
      Restricts the 'ENTER' operation on 'Facility' resources labeled 'location: 
      "production-room"' to users possessing the 'training-vde-available-group' attribute. 
      This restriction is only enforced during a critical, 
      specific time window (2025-10-20T08:00:00Z to 2025-10-20T09:00:00Z) for members of the 'employee-group'.
spec:
  validationFailureAction: Enforce # Immediately block request
  background: false
  rules:
    - name: deny-enroll-without-training-vde
      match:
        # 1. Subject Attribute: The group must be 'employee-group'
        any: # Match any resource of the following kinds
        # 2. Resource Attribute: The target resource must be one of the locations
        resources:
          kinds:
            - Facility # Example: A Custom Resource for physical facilities

      # TEMPORAL PRECONDITION: The rule is ONLY executed if the time is within the single, absolute window.
      preconditions:
        all:
          # Use time_between() for a single, absolute date and time range.
          - key: "{{ time_between('{{ request.time.admissionTime }}', '2024-10-20T08:00:00Z', '2026-10-20T19:00:00Z') }}"
            operator: Equals
            value: true

      validate:
        message: "ATTENTION: The 'UPDATE' operation is only allowed for qualified personnel ('training-vde-available') during the critical time window (08:00-09:00 UTC)."
        deny: # Deny the request UNLESS all required conditions are met
          conditions:
            # Deny if EITHER of these is true (i.e., not allowed):
            any:
              # Condition B: Deny if the user is NOT in the required group
              - key: training-vde-available-group
                operator: NotIn
                value: "{{ request.userInfo.groups }}"